# NumPy Retail Analytics Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.

---

# Part 1: Dataset Creation

```python
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)
```

---

In [1]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

---


In [2]:
stores_count=np.size(stores)
categories_count=np.size(categories)
dimension_sales_data=np.ndim(sales_data)
shape_sales_data=np.shape(sales_data)
values_sales_data=np.size(sales_data)
values_cost_data=np.size(cost_data)
dtype_sales_data=sales_data.dtype
dtype_cost_data=cost_data.dtype
dtype_stores=stores.dtype
dtype_categories=categories.dtype
memory_sales_data=sales_data.nbytes
memory_cost_data=cost_data.nbytes
print("No of stores :",stores_count)
print("No of categories :",categories_count)
print("Dimensions of sales_data:", dimension_sales_data)
print("Shape of sales_data:", shape_sales_data)
print("Total number of values in sales_data:", values_sales_data)
print("Total number of values in cost_data:", values_cost_data)
print("Data type of sales_data:", dtype_sales_data)
print("Data type of cost_data:", dtype_cost_data )

No of stores : 5
No of categories : 6
Dimensions of sales_data: 2
Shape of sales_data: (5, 6)
Total number of values in sales_data: 30
Total number of values in cost_data: 30
Data type of sales_data: int64
Data type of cost_data: int64


## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

---

In [3]:
print("No of stores :",stores_count)
print("No of categories :",categories_count)
print("Total number of store-category combinations :",stores_count*categories_count)


No of stores : 5
No of categories : 6
Total number of store-category combinations : 30


## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

---

In [4]:
sales_data_float32 = sales_data.astype('float32')
sales_data_float64 = sales_data.astype('float64')
memory_sales_data_float32 = sales_data_float32.nbytes
memory_sales_data_float64 = sales_data_float64.nbytes
print("Memory used by sales_data (float32):", memory_sales_data_float32)
print("Memory used by sales_data (float64):", memory_sales_data_float64)

Memory used by sales_data (float32): 120
Memory used by sales_data (float64): 240


# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

---

In [5]:
print(stores)
print(categories)


['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']


In [6]:
print("complete sales row for Bengaluru : ",sales_data[0].tolist())

complete sales row for Bengaluru :  [850000, 420000, 310000, 275000, 190000, 225000]


## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

---

In [7]:
print(stores[3])
total = cost_data[3].sum()
print("Total cost incurred by Mumbai store for all product categories:", total)

Mumbai
Total cost incurred by Mumbai store for all product categories: 2065000


## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.

---

In [8]:
print("stores :",stores)
print("Electronics sales across from stores :",sales_data.T[0].tolist())

stores : ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
Electronics sales across from stores : [850000, 780000, 920000, 1050000, 690000]


## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

---

In [9]:
print("Clothing cost across from cost_data  :",cost_data.T[2].tolist())

Clothing cost across from cost_data  : [220000, 210000, 245000, 265000, 205000]


## Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

---

In [10]:
print("Furniture sales of Hyderabad :",sales_data[1,3])
print("Furniture cost of Hyderabad :",cost_data[1,3])
print("Furniture profit of Hyderabd :",sales_data[1,3]-cost_data[1,3])

Furniture sales of Hyderabad : 310000
Furniture cost of Hyderabad : 225000
Furniture profit of Hyderabd : 85000


## Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

---

In [11]:
print("Chennai sales in Groceries :",sales_data[2,1])
print("Chennai sales in Clothing :",sales_data[2,2])
print("Chennai sales in Furniture :",sales_data[2,3])

Chennai sales in Groceries : 390000
Chennai sales in Clothing : 340000
Chennai sales in Furniture : 260000



## Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

---

In [12]:
print(stores)
print(categories)

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']


In [13]:
print(categories[::2])
print("Bengaluru sales :",sales_data[0][::2],"\nChennai sales :",sales_data[2][::2],"\nPune sales :",sales_data[4][::2])

['Electronics' 'Clothing' 'Beauty']
Bengaluru sales : [850000 310000 190000] 
Chennai sales : [920000 340000 185000] 
Pune sales : [690000 280000 175000]



# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

---

In [14]:
print("Total sales revenue :",sales_data.sum())
print("Total sales revenue by all stores :",sales_data.sum(axis=1))
print("Total sales revenue by all categories :",sales_data.sum(axis=0))

Total sales revenue : 11675000
Total sales revenue by all stores : [2270000 2295000 2310000 2820000 1980000]
Total sales revenue by all categories : [4290000 2185000 1600000 1415000 1010000 1175000]


## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

```text
Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales
```

---

In [15]:
print("Total sales revenue for each store :")
print("Bengalure :",sales_data[0].sum(),"\nHyderabad :",sales_data[1].sum(),"\nChennai :",sales_data[2].sum(),"\nMumbai :",sales_data[3].sum(),"\npune :",sales_data[4].sum())

Total sales revenue for each store :
Bengalure : 2270000 
Hyderabad : 2295000 
Chennai : 2310000 
Mumbai : 2820000 
pune : 1980000


In [16]:
store_totals = sales_data.sum(axis=1)
for store,total in zip(stores,store_totals):
  print(store,":",total)

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

---


In [17]:
print("Total sales revenue for each product category :")
for category,total in zip(categories,sales_data.sum(axis=0)):
  print(category ,':', total)

Total sales revenue for each product category :
Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

---

In [18]:
print("Average sales per store :")
for store,avg in zip(stores,sales_data.mean(axis=1)):
  print(store,":",avg)

Average sales per store :
Bengaluru : 378333.3333333333
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

---

In [19]:
print("Average sales per category :")
for category,avg in zip(categories,sales_data.mean(axis=0)):
  print(category,":",avg)

Average sales per category :
Electronics : 858000.0
Groceries : 437000.0
Clothing : 320000.0
Furniture : 283000.0
Beauty : 202000.0
Sports : 235000.0



## Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

Use `np.argmax()`.

---

In [20]:
print("Index of the store with the highest total sales :",np.argmax(sales_data.sum(axis=1)))
print("Name of the store :",stores[np.argmax(sales_data.sum(axis=1))])
print("Total sales generated by that store :",sales_data.sum(axis=1)[np.argmax(sales_data.sum(axis=1))])

Index of the store with the highest total sales : 3
Name of the store : Mumbai
Total sales generated by that store : 2820000


## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use `np.argmin()`.

---


In [21]:
print("Lowest selling store :", stores[np.argmin(sales_data.sum(axis=1))])

Lowest selling store : Pune


## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

---

In [22]:
print("Highest-Selling Category :",categories[np.argmax(sales_data.sum(axis=0))])

Highest-Selling Category : Electronics


## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

---


In [23]:
print("Lowest-Selling Category :",categories[np.argmin(sales_data.sum(axis=0))])

Lowest-Selling Category : Beauty


# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

---

In [24]:
print("Total cost incurred by all stores :",cost_data.sum(axis=1))
print("Total cost incurred by all categories :",cost_data.sum(axis=0))

Total cost incurred by all stores : [1665000 1685000 1710000 2065000 1475000]
Total cost incurred by all categories : [3250000 1660000 1145000 1045000  665000  835000]


## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

---

In [25]:
print("Total cost incurred by each store :")
for store,total in zip(stores,cost_data.sum(axis=1)):
  print(store,":",total)

Total cost incurred by each store :
Bengaluru : 1665000
Hyderabad : 1685000
Chennai : 1710000
Mumbai : 2065000
Pune : 1475000


## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

---

In [26]:
print("Total cost incurred by each category :")
for category,total in zip(categories,cost_data.sum(axis=0)):
  print(category,":",total)

Total cost incurred by each category :
Electronics : 3250000
Groceries : 1660000
Clothing : 1145000
Furniture : 1045000
Beauty : 665000
Sports : 835000



## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

---

In [27]:
print("The store with the highest total operating cost :",stores[np.argmax(cost_data.sum(axis=1))])

The store with the highest total operating cost : Mumbai


## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

---

In [28]:
print("The store with the lowest total operating cost :",stores[np.argmin(cost_data.sum(axis=1))])


The store with the lowest total operating cost : Pune


## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

---

In [29]:
print("Most expensive product category :",categories[np.argmax(cost_data.sum(axis=0))])

Most expensive product category : Electronics


# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

```python
profit_data = sales_data - cost_data
```

Display the complete profit matrix.

---

In [30]:
profit_data = sales_data - cost_data
print("Profit matrix :")
print(profit_data)

Profit matrix :
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

---

In [31]:
print("Total profit generated by each store :")
for store ,total in zip(stores,profit_data.sum(axis=1)):
  print(store,":",total)

Total profit generated by each store :
Bengaluru : 605000
Hyderabad : 610000
Chennai : 600000
Mumbai : 755000
Pune : 505000


## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

---

In [32]:
print("Total profit generated by each product category :")
for category ,total in zip(categories,profit_data.sum(axis=0)):
  print(category,":",total)

Total profit generated by each product category :
Electronics : 1040000
Groceries : 525000
Clothing : 455000
Furniture : 370000
Beauty : 345000
Sports : 340000



## Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

* Store name
* Total sales
* Total cost
* Total profit

---

In [33]:
highest_profit=np.argmax(profit_data.sum(axis=1))
print("The store with the highest total profit :",stores[highest_profit])
print("Total sales of the store :",sales_data[highest_profit].sum())
print("Total cost of the store :",cost_data[highest_profit].sum())
print("Total profit store :",profit_data[highest_profit].sum())

The store with the highest total profit : Mumbai
Total sales of the store : 2820000
Total cost of the store : 2065000
Total profit store : 755000


## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

---

In [34]:
print("The store with the least total profit :",stores[np.argmin(profit_data.sum(axis=1))])

The store with the least total profit : Pune


## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

---

In [35]:
print("The categoer with the highest total profit :",categories[np.argmax(profit_data.sum(axis=0))])

The categoer with the highest total profit : Electronics


## Question 32: Least Profitable Category

Find the category with the lowest total profit.

---


In [36]:
print("The categoer with the lowest total profit :",categories[np.argmin(profit_data.sum(axis=0))])

The categoer with the lowest total profit : Sports


## Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

* Profit amount
* Store name
* Product category

Use `np.unravel_index()`.

---


In [37]:
ivd_profit=np.unravel_index(np.argmax(profit_data),profit_data.shape)
print(ivd_profit)
print("Maximum individual profit :",profit_data[ivd_profit])
print("Store name :",stores[ivd_profit[0]])
print("Product category :",categories[ivd_profit[1]])

(np.int64(3), np.int64(0))
Maximum individual profit : 260000
Store name : Mumbai
Product category : Electronics



---

## Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

---

In [38]:
min_profit=np.unravel_index(np.argmin(profit_data),profit_data.shape)
print("Minimum individual profit :",profit_data[min_profit])
print("Store name :",stores[min_profit[0]])
print("Product category :",categories[min_profit[1]])

Minimum individual profit : 55000
Store name : Pune
Product category : Furniture



# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

```python
profit_margin = (profit_data / sales_data) * 100
```

Round the result to two decimal places.

---


In [39]:
profit_margin = np.round((profit_data/sales_data)*100,2)
print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

```text
Store Profit Margin =
Total Store Profit / Total Store Sales × 100
```

---

In [40]:
Total_store_sales=sales_data.sum(axis=1)
Total_store_profit=profit_data.sum(axis=1)
store_profit_margin=np.round(Total_store_profit / Total_store_sales * 100,2)
for store,profit in zip(stores,store_profit_margin):
  print(store,":",profit)

Bengaluru : 26.65
Hyderabad : 26.58
Chennai : 25.97
Mumbai : 26.77
Pune : 25.51


## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

---

In [41]:
Total_category_sales=sales_data.sum(axis=0)
Total_category_profit=profit_data.sum(axis=0)
category_profit_margin=np.round(Total_category_profit / Total_category_sales * 100,2)
for category,profit in zip(categories,category_profit_margin):
  print(category,":",profit)

Electronics : 24.24
Groceries : 24.03
Clothing : 28.44
Furniture : 26.15
Beauty : 34.16
Sports : 28.94


## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

---

In [42]:
print("The store with the highest overall profit margin :",stores[np.argmax(profit_margin.sum(axis=1))])

The store with the highest overall profit margin : Mumbai


## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

---


In [43]:
print("The category with the highest overall profit margin :",categories[np.argmax(profit_margin.sum(axis=0))])

The category with the highest overall profit margin : Beauty



## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

* Store
* Category
* Sales
* Cost
* Profit
* Profit margin

Use Boolean indexing.

---


In [44]:
weak_profit=profit_margin < 22
print(profit_margin[weak_profit])

[]


# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

---

In [45]:
high_sales = sales_data > 500000
print(sales_data[high_sales])

[ 850000  780000  920000 1050000  510000  690000]


## Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

---

In [46]:
low_sales = sales_data < 200000
print(sales_data[low_sales])

[190000 185000 175000]


## Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

---

In [47]:
print("High profit values :",profit_data[np.where(profit_data > 150000)])

High profit values : [210000 190000 220000 260000 160000]


## Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use `np.logical_and()`.

---

In [48]:
print("Moderate range sales :",sales_data[np.logical_and(sales_data > 250000 , sales_data < 500000)])

Moderate range sales : [420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 290000 405000 280000]



## Question 45: Premium Performance

A store-category combination is considered premium when:

* Sales are greater than ₹5,00,000
* Profit is greater than ₹1,50,000

Find all premium-performing combinations.

---


In [49]:
premium_sales = sales_data[np.logical_and(sales_data > 500000 , profit_data > 150000)]
print("Premium performing combinations :",premium_sales)

Premium performing combinations : [ 850000  780000  920000 1050000  690000]



## Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

* Sales are below ₹2,50,000
* Profit margin is below 25%

Find all such combinations.

---

In [50]:
print("Underperforming peerformance :",sales_data[np.logical_and(sales_data < 250000,profit_margin < 25)])

Underperforming peerformance : [225000]



## Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

* `"High"` when sales are at least ₹5,00,000
* `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
* `"Low"` when sales are below ₹2,50,000

Use `np.where()` or `np.select()`.

---


In [51]:
category_performance = np.where(sales_data >= 500000,"High",np.where((sales_data > 250000) & (sales_data <499999), "Medium" ,"Low"  ))
print(category_performance)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Low' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]



# Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

```python
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
```


In [52]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
print(sales_targets)

[800000 450000 320000 300000 200000 230000]



## Question 48: Target Comparison

Compare every store’s category sales against `sales_targets`.

Use NumPy broadcasting.

---


In [53]:
comparison = sales_data >= sales_targets
print(comparison)


[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


## Question 49: Target Achievement Matrix

Create a Boolean array where:

* `True` means the store achieved the category target
* `False` means the store failed to achieve the target

---


In [54]:
print(comparison)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


## Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

---


In [55]:
print("Target Achievement count :",np.count_nonzero(comparison == True))

Target Achievement count : 13


## Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

---

In [56]:
print("The store that achieved the highest number of category targets :",stores[np.argmax(np.count_nonzero(comparison,axis=1))])

The store that achieved the highest number of category targets : Mumbai


## Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

---

In [57]:
print("Store achieved the target for each product :")
for category,target in zip(categories,np.count_nonzero(comparison,axis=0)):
  print(category,":",target)

Store achieved the target for each product :
Electronics : 3
Groceries : 2
Clothing : 2
Furniture : 2
Beauty : 2
Sports : 2


## Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:

```text
Variance = Actual Sales - Target Sales
```

---

In [58]:
target_variance = sales_data - sales_targets
print(target_variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


## Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

```text
Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100
```

---


In [59]:
variance_percentage = np.round((sales_data - sales_targets)/sales_targets * 100 , 2)
print(variance_percentage)

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


## Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

---

In [60]:
failed_electronics = stores[np.where(variance_percentage[:,0] < 0)]
print(failed_electronics)

['Hyderabad' 'Pune']


## Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use `np.all()`.

---


In [61]:
print("Stores Achieving all targets :",stores[np.all(comparison,axis=1)])

Stores Achieving all targets : ['Mumbai']


## Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use `np.any()`.

---


In [62]:
print("Stores that achieved at least one category target :",stores[np.any(comparison,axis=1)])

Stores that achieved at least one category target : ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']



# Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:
```python
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
```


In [63]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
print(discount_rates)

[0.1  0.05 0.15 0.12 0.08 0.1 ]



## Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

---


In [64]:
discount_amount = sales_data * discount_rates
discount_amounts = np.astype(discount_amount,int)
print(discount_amounts)

[[ 85000  21000  46500  33000  15200  22500]
 [ 78000  23000  44250  37200  16800  24000]
 [ 92000  19500  51000  31200  14800  21500]
 [105000  25500  56250  41400  20000  29000]
 [ 69000  20250  42000  27000  14000  20500]]


## Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

---

In [65]:
net_sales = sales_data - discount_amounts
print(net_sales)

[[765000 399000 263500 242000 174800 202500]
 [702000 437000 250750 272800 193200 216000]
 [828000 370500 289000 228800 170200 193500]
 [945000 484500 318750 303600 230000 261000]
 [621000 384750 238000 198000 161000 184500]]


## Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

---


In [66]:
new_profits = net_sales - cost_data
print(new_profits)

[[125000  84000  43500  37000  49800  42500]
 [112000  87000  40750  47800  53200  46000]
 [128000  75500  44000  33800  50200  38500]
 [155000  94500  53750  53600  65000  56000]
 [ 91000  74750  33000  28000  46000  39500]]


## Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

---

In [67]:
new_profit_margin = np.round((new_profits/sales_data)*100,2)
print(new_profit_margin)

[[14.71 20.   14.03 13.45 26.21 18.89]
 [14.36 18.91 13.81 15.42 25.33 19.17]
 [13.91 19.36 12.94 13.   27.14 17.91]
 [14.76 18.53 14.33 15.54 26.   19.31]
 [13.19 18.46 11.79 12.44 26.29 19.27]]


## Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

---


In [68]:
loss_making = new_profits < 0
print(loss_making)
print(stores[np.any(loss_making, axis =1)])
print(categories[np.any(loss_making,axis=0)])

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
[]
[]


## Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

---

In [69]:
discount_impact = sales_data - net_sales
print(discount_impact)

[[ 85000  21000  46500  33000  15200  22500]
 [ 78000  23000  44250  37200  16800  24000]
 [ 92000  19500  51000  31200  14800  21500]
 [105000  25500  56250  41400  20000  29000]
 [ 69000  20250  42000  27000  14000  20500]]


## Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

---


In [70]:
affected_store = np.unravel_index(np.argmax(discount_impact),discount_impact.shape)
print("Most affected store by discount :",stores[affected_store[0]])

Most affected store by discount : Mumbai


# Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

```python
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
```

In [71]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
print(tax_rates)

[0.18 0.05 0.12 0.18 0.18 0.12]



## Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

---


In [72]:
tax_amount = net_sales * tax_rates
tax_amounts = np.astype(tax_amount,int)
print(tax_amounts)

[[137700  19950  31620  43560  31464  24300]
 [126360  21850  30090  49104  34776  25920]
 [149040  18525  34680  41184  30636  23220]
 [170100  24225  38250  54648  41400  31320]
 [111780  19237  28560  35640  28980  22140]]



## Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

---


In [73]:
sales_with_tax = net_sales + tax_amounts
print(sales_with_tax)

[[ 902700  418950  295120  285560  206264  226800]
 [ 828360  458850  280840  321904  227976  241920]
 [ 977040  389025  323680  269984  200836  216720]
 [1115100  508725  357000  358248  271400  292320]
 [ 732780  403987  266560  233640  189980  206640]]


## Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

---

In [74]:
print("Store-wise tax collection :")
for store,tax in zip(stores,np.sum(tax_amounts,axis =1)):
  print(store,":",tax)

Store-wise tax collection :
Bengaluru : 288594
Hyderabad : 288100
Chennai : 297285
Mumbai : 359943
Pune : 246337


## Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

---


In [75]:
print("Category-wise tax collection :")
for category,tax in zip(categories,np.sum(tax_amounts,axis=0)):
  print(category,":",tax)

Category-wise tax collection :
Electronics : 694980
Groceries : 103787
Clothing : 163200
Furniture : 224136
Beauty : 167256
Sports : 126900


## Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

---

In [76]:
print("Highest Tax-contributing store :",stores[np.argmax(np.sum(tax_amounts,axis = 1))])

Highest Tax-contributing store : Mumbai



# Part 12: Array Modification

## Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

---


In [77]:
updated_sales = np.copy(sales_data)
updated_sales[4,0] = 740000
print("Updated pune electronics sales :")
print(updated_sales)

Updated pune electronics sales :
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


## Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

---


In [78]:
updated_cost = np.copy(cost_data)

# Apply 8% reduction to Beauty column (index 4)
updated_cost[:,4] = np.round(updated_cost[:,4] * 0.92).astype(int)

print("Original Cost Data:\n", cost_data)
print("\nUpdated Cost Data:\n", updated_cost)


Original Cost Data:
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

Updated Cost Data:
 [[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


## Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

---

In [83]:
updated_cost[:,3] = np.round(updated_cost[:,3] * 1.12).astype(int)
#updated the furtinure category of cost by 12%
print(updated_cost)

[[640000 315000 220000 288010 115000 160000]
 [590000 350000 210000 316109 128800 170000]
 [700000 295000 245000 273961 110400 155000]
 [790000 390000 265000 351232 151800 205000]
 [530000 310000 205000 238838 105800 145000]]


## Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using `np.delete()`.

---

In [95]:
updated_sales_data  = np.copy(sales_data)
updated_cost_data = np.copy(cost_data)
updated_sales_data = np.delete(updated_sales_data,4,axis = 0)
updated_cost_data = np.delete(updated_cost_data,4,axis=0)
print("Updated sales data after pune removed:")
print(updated_sales_data)
print("\nUpdated cost data after pune removed:")
print(updated_cost_data)
updated_stores = np.delete(stores,4)

Updated sales data after pune removed:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]

Updated cost data after pune removed:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]



## Question 74: Adding a New Store

A new Delhi store is opened with the following data:

```python
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
```

Add Delhi to both arrays using `np.vstack()`.

Also add `"Delhi"` to the stores array.

---


In [138]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
updated_cost_data = np.vstack((updated_cost_data,delhi_cost))
updated_sales_data = np.vstack((updated_sales_data,delhi_sales))
updated_stores = np.append(updated_stores,"Delhi")
print("Updated sales data after adding delhi:")
print(updated_sales_data)
print("\nUpdated cost data after adding delhi:")
print(updated_cost_data)



Updated sales data after adding delhi:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 880000  475000  330000  290000  215000  250000]]

Updated cost data after adding delhi:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [665000 360000 235000 215000 145000 180000]]


In [142]:
updated_stores = np.delete(updated_stores,4,axis = 0)
print(updated_stores)
#

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Delhi']


## Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

```python
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
```

Add the new category as a column using `np.column_stack()` or `np.hstack()`.

---


In [173]:
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
updated_sales_data = np.column_stack((updated_sales_data,home_appliance_sales))
updated_cost_data = np.column_stack((updated_cost_data,home_appliance_cost))
print("Updated sales data after adding home appliances:")
print(updated_sales_data)
print("\nUpdated cost data after adding home appliances:")
print(updated_cost_data)
#

Updated sales data after adding home appliances:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 880000  475000  330000  290000  215000  205000  295000]]

Updated cost data after adding home appliances:
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [665000 360000 235000 215000 145000 145000 225000]]


In [175]:
updated_categories = np.copy(categories)

In [176]:
updated_categories=np.append(updated_categories,"Home Appliances")
print(updated_categories)

['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']


# Part 13: Sorting and Ranking

## Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

---


In [177]:
total_sales = np.sum(updated_sales_data,axis=1)
sorted_indices = np.argsort(total_sales)
sorted_stores = updated_stores[sorted_indices]
sorted_sales = total_sales[sorted_indices]
for store,sales in zip(sorted_stores,sorted_sales):
  print(store,":",sales)

Hyderabad : 2620000
Bengaluru : 2630000
Delhi : 2690000
Chennai : 2700000
Mumbai : 3240000


## Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use `np.argsort()`.

---

In [ ]:
updated_profit_data = updated_sales_data - updated_cost_data
store_profit_totals = updated_profit_data.sum(axis=1)
rank_order = np.argsort(store_profit_totals)[::-1]
print("Stores ranked by total profit (highest to lowest):")
for rank, i in enumerate(rank_order, start=1):
  print(rank,":",updated_stores[i],":",store_profit_totals[i])

Stores ranked by total profit (highest to lowest):
1 : Mumbai : 870000
2 : Delhi : 710000
3 : Chennai : 705000
4 : Bengaluru : 700000
5 : Hyderabad : 695000


## Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

---

In [ ]:
category_revenue = updated_sales_data.sum(axis=0)
rank_order = np.argsort(category_revenue)[::-1]
print("Categories sorted by total revenue (highest to lowest):")
for i in rank_order:
  print(updated_categories[i],":",category_revenue[i])

Categories sorted by total revenue (highest to lowest):
Electronics : 4480000
Groceries : 2255000
Home Appliances : 1790000
Clothing : 1650000
Furniture : 1480000
Sports : 1220000
Beauty : 1050000


## Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

* Sales value
* Store name
* Category name

---

In [ ]:
top3_flat = np.argsort(updated_sales_data.ravel())[::-1][:3]
rows,cols = np.unravel_index(top3_flat,updated_sales_data.shape)
print("Top 3 individual sales values:")
for r,c in zip(rows,cols):
  print(updated_stores[r],"-",updated_categories[c],":",updated_sales_data[r,c])

Top 3 individual sales values:
Mumbai - Electronics : 1050000
Chennai - Electronics : 920000
Delhi - Electronics : 880000


## Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

---

In [ ]:
bottom3_flat = np.argsort(updated_profit_data.ravel())[:3]
rows,cols = np.unravel_index(bottom3_flat,updated_profit_data.shape)
print("Bottom 3 profit values:")
for r,c in zip(rows,cols):
  print(updated_stores[r],"-",updated_categories[c],":",updated_profit_data[r,c])

Bottom 3 profit values:
Chennai - Sports : 60000
Bengaluru - Sports : 65000
Chennai - Furniture : 65000


# Part 14: Statistical Analysis

## Question 81: Sales Statistics

Calculate the following for the complete sales array:

* Minimum
* Maximum
* Mean
* Median
* Standard deviation
* Variance
* 25th percentile
* 50th percentile
* 75th percentile

---

In [ ]:
print("Minimum :",sales_data.min())
print("Maximum :",sales_data.max())
print("Mean :",np.round(sales_data.mean(),2))
print("Median :",np.median(sales_data))
print("Standard deviation :",np.round(sales_data.std(),2))
print("Variance :",np.round(sales_data.var(),2))
print("25th percentile :",np.percentile(sales_data,25))
print("50th percentile :",np.percentile(sales_data,50))
print("75th percentile :",np.percentile(sales_data,75))

Minimum : 175000
Maximum : 1050000
Mean : 389166.67
Median : 302500.0
Standard deviation : 230322.54
Variance : 53048472222.22
25th percentile : 228750.0
50th percentile : 302500.0
75th percentile : 416250.0


## Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

---

In [ ]:
store_std = sales_data.std(axis=1)
for store,std in zip(stores,store_std):
  print(store,":",np.round(std,2))
print("\nStore with most variation across categories :",stores[np.argmax(store_std)])

Bengaluru : 223059.53
Hyderabad : 194502.57
Chennai : 249265.59
Mumbai : 271860.87
Pune : 177200.45

Store with most variation across categories : Mumbai


## Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

---

In [ ]:
category_std = sales_data.std(axis=0)
for category,std in zip(categories,category_std):
  print(category,":",np.round(std,2))
print("\nCategory with highest variation across stores :",categories[np.argmax(category_std)])

Electronics : 122539.79
Groceries : 43312.82
Clothing : 33911.65
Furniture : 41303.75
Beauty : 26570.66
Sports : 29832.87

Category with highest variation across stores : Electronics


## Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

---

In [ ]:
company_avg = sales_data.mean()
above_avg_count = np.sum(sales_data > company_avg)
print("Company-wide average sales :",np.round(company_avg,2))
print("Number of values above average :",above_avg_count)

Company-wide average sales : 389166.67
Number of values above average : 10


## Question 85: Outlier Detection

Treat any sales value greater than Mean + 1.5 × Standard Deviation as a high-value outlier.

Identify all such sales values.

---

In [ ]:
threshold = sales_data.mean() + 1.5*sales_data.std()
outliers = sales_data[sales_data > threshold]
print("Outlier threshold :",np.round(threshold,2))
print("Outlier sales values :",outliers)

Outlier threshold : 734650.48
Outlier sales values : [ 850000  780000  920000 1050000]


# Part 15: Reshaping and Transformation

## Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

* `flatten()`
* `ravel()`

Explain the difference between the two methods.

---

In [ ]:
flat1 = sales_data.flatten()
flat2 = sales_data.ravel()
print("flatten() :",flat1)
print("ravel() :",flat2)
print("Both equal :",np.array_equal(flat1,flat2))

# Difference: flatten() always returns a new copy of the data, so changing it
# never affects the original array. ravel() returns a view of the original
# array whenever possible (only makes a copy if the array is not contiguous),
# so it is faster/uses less memory, but changing its output can change the
# original array.
flat2[0] = -1
print("After editing ravel() output, sales_data[0,0] :",sales_data[0,0])
sales_data[0,0] = 850000

flatten() : [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
ravel() : [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Both equal : True
After editing ravel() output, sales_data[0,0] : -1


## Question 87: Reshape Sales Data

Reshape the `5 × 6` sales array into:

* `3 × 10`
* `10 × 3`
* `2 × 15`
* `15 × 2`

Verify that no data is lost.

---

In [ ]:
for shape in [(3,10),(10,3),(2,15),(15,2)]:
  reshaped = sales_data.reshape(shape)
  print("Shape",shape,":")
  print(reshaped)
  print("Data preserved :",np.array_equal(reshaped.ravel(),sales_data.ravel()))
  print()

Shape (3, 10) :
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
Data preserved : True

Shape (10, 3) :
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
Data preserved : True

Shape (2, 15) :
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
Data preserved : True

Shape (15, 2) :
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  31

## Question 88: Transpose Sales Data

Transpose the sales array so that:

* Rows represent product categories
* Columns represent stores

Display the new shape.

---

In [ ]:
sales_transposed = sales_data.T
print("Original shape :",sales_data.shape)
print("Transposed shape :",sales_transposed.shape)
print(sales_transposed)

Original shape : (5, 6)
Transposed shape : (6, 5)
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


## Question 89: Combined Sales and Cost Array

Stack `sales_data` and `cost_data` vertically.

Display the resulting shape.

---

In [ ]:
combined = np.vstack((sales_data,cost_data))
print("Combined shape :",combined.shape)
print(combined)

Combined shape : (10, 6)
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]


## Question 90: Store-Level Combined Data

Create a three-dimensional array where:

* First layer contains sales data
* Second layer contains cost data

Use `np.stack()`.

Display the shape of the new array.

---

In [ ]:
combined_3d = np.stack((sales_data,cost_data))
print("Shape of 3D array :",combined_3d.shape)
print("Layer 0 matches sales_data :",np.array_equal(combined_3d[0],sales_data))
print("Layer 1 matches cost_data :",np.array_equal(combined_3d[1],cost_data))

Shape of 3D array : (2, 5, 6)
Layer 0 matches sales_data : True
Layer 1 matches cost_data : True


# Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

In [ ]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
print(sales_with_missing)

[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]


## Question 91: Missing Value Detection

Find:

* Total number of missing values
* Location of missing values
* Stores and categories containing missing values

---

In [ ]:
missing_mask = np.isnan(sales_with_missing)
print("Total missing values :",np.sum(missing_mask))
rows,cols = np.where(missing_mask)
print("\nLocations of missing values :")
for r,c in zip(rows,cols):
  print("  (",r,",",c,") ->",stores[r],"-",categories[c])

Total missing values : 4

Locations of missing values :
  ( 0 , 2 ) -> Bengaluru - Clothing
  ( 1 , 3 ) -> Hyderabad - Furniture
  ( 3 , 1 ) -> Mumbai - Groceries
  ( 4 , 4 ) -> Pune - Beauty


## Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

---

In [ ]:
sales_filled_zero = np.nan_to_num(sales_with_missing,nan=0.0)
print(sales_filled_zero)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


## Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use `np.nanmean()`.

---

In [ ]:
overall_avg = np.nanmean(sales_with_missing)
sales_filled_avg = np.where(np.isnan(sales_with_missing),overall_avg,sales_with_missing)
print("Overall average (excluding NaN) :",np.round(overall_avg,2))
print(sales_filled_avg)

Overall average (excluding NaN) : 398846.15
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


## Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

---

In [ ]:
category_avg = np.nanmean(sales_with_missing,axis=0)
sales_filled_cat = sales_with_missing.copy()
rows,cols = np.where(np.isnan(sales_with_missing))
for r,c in zip(rows,cols):
  sales_filled_cat[r,c] = category_avg[c]
print("Category averages (excluding NaN) :",np.round(category_avg,2))
print(sales_filled_cat)

Category averages (excluding NaN) : [858000. 418750. 322500. 276250. 208750. 235000.]
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


## Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

---

In [ ]:
total_ignoring_nan = np.nansum(sales_with_missing)
total_after_zero = np.sum(np.nan_to_num(sales_with_missing,nan=0.0))
print("Total sales ignoring NaN (nansum) :",total_ignoring_nan)
print("Total sales after replacing NaN with 0 :",total_after_zero)
print("Difference :",total_ignoring_nan - total_after_zero)

Total sales ignoring NaN (nansum) : 10370000.0
Total sales after replacing NaN with 0 : 10370000.0
Difference : 0.0


# Part 17: Conditional Business Decisions

## Question 96: Store Performance Labels

Classify each store based on total sales:

* `"Excellent"`: Total sales above ₹28,00,000
* `"Good"`: Total sales between ₹24,00,000 and ₹28,00,000
* `"Needs Improvement"`: Total sales below ₹24,00,000

Use `np.select()`.

---

In [ ]:
store_totals = sales_data.sum(axis=1)
conditions = [store_totals > 2800000,(store_totals >= 2400000) & (store_totals <= 2800000)]
choices = ["Excellent","Good"]
store_labels = np.select(conditions,choices,default="Needs Improvement")
for store,total,label in zip(stores,store_totals,store_labels):
  print(store,":",total,":",label)

Bengaluru : 2270000 : Needs Improvement
Hyderabad : 2295000 : Needs Improvement
Chennai : 2310000 : Needs Improvement
Mumbai : 2820000 : Excellent
Pune : 1980000 : Needs Improvement


## Question 97: Profitability Classification

Classify each store-category combination as:

* `"Highly Profitable"`: Profit above ₹2,00,000
* `"Profitable"`: Profit between ₹1,00,000 and ₹2,00,000
* `"Low Profit"`: Profit below ₹1,00,000
* `"Loss"`: Profit below zero

---

In [ ]:
conditions = [
    profit_data < 0,
    (profit_data >= 0) & (profit_data < 100000),
    (profit_data >= 100000) & (profit_data <= 200000),
    profit_data > 200000
]
choices = ["Loss","Low Profit","Profitable","Highly Profitable"]
profitability_labels = np.select(conditions,choices,default="Low Profit")
print(profitability_labels)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


## Question 98: Expansion Recommendation

A store is eligible for expansion when:

* Total sales are above ₹25,00,000
* Total profit is above ₹7,00,000
* Overall profit margin is above 25%

---

In [ ]:
store_sales_total = sales_data.sum(axis=1)
store_profit_total = profit_data.sum(axis=1)
store_margin_total = (store_profit_total/store_sales_total)*100
eligible = (store_sales_total > 2500000) & (store_profit_total > 700000) & (store_margin_total > 25)
print("Stores eligible for expansion :",stores[eligible])

Stores eligible for expansion : ['Mumbai']


## Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

* Average sales are below ₹3,00,000
* Profit margin is above 25%

---

In [ ]:
category_avg_sales = sales_data.mean(axis=0)
category_margin_total = (profit_data.sum(axis=0)/sales_data.sum(axis=0))*100
promo = (category_avg_sales < 300000) & (category_margin_total > 25)
print("Categories recommended for promotion :",categories[promo])

Categories recommended for promotion : ['Furniture' 'Beauty' 'Sports']


## Question 100: Cost Optimization Recommendation

Find store-category combinations where:

* Cost is greater than ₹2,50,000
* Profit margin is below 25%

---

In [ ]:
cost_opt = (cost_data > 250000) & (profit_margin < 25)
rows,cols = np.where(cost_opt)
for r,c in zip(rows,cols):
  print(stores[r],"-",categories[c],": Cost=",cost_data[r,c],": Margin=",profit_margin[r,c],"%")

Bengaluru - Electronics : Cost= 640000 : Margin= 24.71 %
Hyderabad - Electronics : Cost= 590000 : Margin= 24.36 %
Hyderabad - Groceries : Cost= 350000 : Margin= 23.91 %
Chennai - Electronics : Cost= 700000 : Margin= 23.91 %
Chennai - Groceries : Cost= 295000 : Margin= 24.36 %
Mumbai - Electronics : Cost= 790000 : Margin= 24.76 %
Mumbai - Groceries : Cost= 390000 : Margin= 23.53 %
Pune - Electronics : Cost= 530000 : Margin= 23.19 %
Pune - Groceries : Cost= 310000 : Margin= 23.46 %


# Part 18: Inventory Scenario

Use the following inventory arrays.

In [ ]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
print("Opening stock :")
print(opening_stock)
print("Units sold :")
print(units_sold)

Opening stock :
[[120 450 300  90 250 180]
 [110 500 280 100 270 200]
 [130 420 320  85 240 170]
 [150 550 350 120 300 220]
 [100 400 260  75 220 160]]
Units sold :
[[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


## Question 101: Closing Stock

Calculate closing stock using: Closing Stock = Opening Stock - Units Sold.

---

In [ ]:
closing_stock = opening_stock - units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


## Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

---

In [ ]:
low_stock = closing_stock < 30
rows,cols = np.where(low_stock)
for r,c in zip(rows,cols):
  print(stores[r],"-",categories[c],":",closing_stock[r,c])

Bengaluru - Electronics : 25
Bengaluru - Furniture : 25
Hyderabad - Electronics : 25
Hyderabad - Furniture : 25
Chennai - Electronics : 25
Chennai - Furniture : 25
Mumbai - Electronics : 25
Pune - Electronics : 25
Pune - Furniture : 20


## Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

---

In [ ]:
availability_pct = np.round((closing_stock/opening_stock)*100,2)
print(availability_pct)

[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


## Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

---

In [ ]:
sold_pct = (units_sold/opening_stock)*100
fast_moving = sold_pct > 80
rows,cols = np.where(fast_moving)
for r,c in zip(rows,cols):
  print(stores[r],"-",categories[c],":",np.round(sold_pct[r,c],2),"% sold")

Bengaluru - Groceries : 84.44 % sold
Hyderabad - Groceries : 84.0 % sold
Hyderabad - Clothing : 82.14 % sold
Chennai - Electronics : 80.77 % sold
Chennai - Groceries : 83.33 % sold
Chennai - Clothing : 84.38 % sold
Mumbai - Electronics : 83.33 % sold
Mumbai - Groceries : 85.45 % sold
Mumbai - Clothing : 84.29 % sold
Pune - Groceries : 82.5 % sold


## Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

---

In [ ]:
category_units = units_sold.sum(axis=0)
for category,total in zip(categories,category_units):
  print(category,":",total)

Electronics : 485
Groceries : 1950
Clothing : 1240
Furniture : 345
Beauty : 980
Sports : 720


## Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

---

In [ ]:
store_units = units_sold.sum(axis=1)
for store,total in zip(stores,store_units):
  print(store,":",total)

Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950


## Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

---

In [ ]:
print("Store with highest units sold :",stores[np.argmax(store_units)])

Store with highest units sold : Mumbai


## Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

---

In [ ]:
reorder_matrix = closing_stock < 25
print(reorder_matrix)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


## Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

---

In [ ]:
reorder_quantity = np.where(closing_stock < 25,100-closing_stock,0)
print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


# Part 19: Advanced NumPy Questions

## Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using `np.cumsum()`.

---

In [ ]:
cumulative_store_sales = np.cumsum(sales_data,axis=1)
print(cumulative_store_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


## Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

---

In [ ]:
cumulative_company_sales = np.cumsum(sales_data.ravel())
print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


## Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using `np.diff()`.

---

In [ ]:
category_diff = np.diff(sales_data,axis=1)
print(category_diff)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


## Question 113: Unique Sales Values

Find all unique sales values in `sales_data`.

Also count the frequency of each value.

---

In [ ]:
unique_vals,counts = np.unique(sales_data,return_counts=True)
for val,cnt in zip(unique_vals,counts):
  print(val,":",cnt,"time(s)")

175000 : 1 time(s)
185000 : 1 time(s)
190000 : 1 time(s)
205000 : 1 time(s)
210000 : 1 time(s)
215000 : 1 time(s)
225000 : 2 time(s)
240000 : 1 time(s)
250000 : 1 time(s)
260000 : 1 time(s)
275000 : 1 time(s)
280000 : 1 time(s)
290000 : 1 time(s)
295000 : 1 time(s)
310000 : 2 time(s)
340000 : 1 time(s)
345000 : 1 time(s)
375000 : 1 time(s)
390000 : 1 time(s)
405000 : 1 time(s)
420000 : 1 time(s)
460000 : 1 time(s)
510000 : 1 time(s)
690000 : 1 time(s)
780000 : 1 time(s)
850000 : 1 time(s)
920000 : 1 time(s)
1050000 : 1 time(s)


## Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

---

In [ ]:
exists = np.any(sales_data == 420000)
print("420000 exists :",exists)
if exists:
  rows,cols = np.where(sales_data == 420000)
  for r,c in zip(rows,cols):
    print("Found at",stores[r],"-",categories[c])

420000 exists : True
Found at Bengaluru - Groceries


## Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using `np.all()`.

---

In [ ]:
sales_gt_cost = sales_data > cost_data
print(sales_gt_cost)
print("\nAll combinations profitable :",np.all(sales_gt_cost))

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]

All combinations profitable : True


## Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

* Minimum: ₹75,000
* Maximum: ₹2,50,000

Use `np.clip()` to create a reporting profit array.

---

In [ ]:
clipped_profit = np.clip(profit_data,75000,250000)
print(clipped_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


## Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

Normalized Sales = (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

---

In [ ]:
normalized_sales = (sales_data - sales_data.min())/(sales_data.max()-sales_data.min())
print(np.round(normalized_sales,4))

[[0.7714 0.28   0.1543 0.1143 0.0171 0.0571]
 [0.6914 0.3257 0.1371 0.1543 0.04   0.0743]
 [0.8514 0.2457 0.1886 0.0971 0.0114 0.0457]
 [1.     0.3829 0.2286 0.1943 0.0857 0.1314]
 [0.5886 0.2629 0.12   0.0571 0.     0.0343]]


## Question 118: Standardize Sales Data

Standardize sales using:

Standardized Sales = (Sales - Mean Sales) / Standard Deviation

---

In [ ]:
standardized_sales = (sales_data - sales_data.mean())/sales_data.std()
print(np.round(standardized_sales,4))

[[ 2.0008  0.1339 -0.3437 -0.4957 -0.8647 -0.7128]
 [ 1.6969  0.3075 -0.4088 -0.3437 -0.7779 -0.6476]
 [ 2.3047  0.0036 -0.2135 -0.5608 -0.8864 -0.7562]
 [ 2.8692  0.5246 -0.0615 -0.1918 -0.6042 -0.4306]
 [ 1.3061  0.0687 -0.474  -0.7128 -0.9299 -0.7996]]


## Question 119: Round Values

Convert profit margin values into:

* Two decimal places
* Nearest whole number
* Floor values
* Ceiling values

---

In [ ]:
print("Two decimal places :")
print(np.round(profit_margin,2))
print("\nNearest whole number :")
print(np.round(profit_margin,0))
print("\nFloor values :")
print(np.floor(profit_margin))
print("\nCeiling values :")
print(np.ceil(profit_margin))

Two decimal places :
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Nearest whole number :
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Floor values :
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Ceiling values :
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


## Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

* `sales_data.npy`
* `cost_data.npy`
* `profit_data.npy`

Load them back and verify that the loaded arrays are equal to the original arrays.

---

In [ ]:
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit_data)

loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")

print("sales_data matches loaded file :",np.array_equal(sales_data,loaded_sales))
print("cost_data matches loaded file :",np.array_equal(cost_data,loaded_cost))
print("profit_data matches loaded file :",np.array_equal(profit_data,loaded_profit))

sales_data matches loaded file : True
cost_data matches loaded file : True
profit_data matches loaded file : True


# Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

## Company Summary

In [ ]:
total_sales = sales_data.sum()
total_cost = cost_data.sum()
total_profit = profit_data.sum()
overall_margin = np.round((total_profit/total_sales)*100,2)
avg_transaction = np.round(sales_data.mean(),2)
highest_sale = sales_data.max()
lowest_sale = sales_data.min()

print("COMPANY SUMMARY")
print("Total Sales :",total_sales)
print("Total Cost :",total_cost)
print("Total Profit :",total_profit)
print("Overall Profit Margin :",overall_margin,"%")
print("Average Transaction Value :",avg_transaction)
print("Highest Individual Sales Value :",highest_sale)
print("Lowest Individual Sales Value :",lowest_sale)

COMPANY SUMMARY
Total Sales : 11675000
Total Cost : 8600000
Total Profit : 3075000
Overall Profit Margin : 26.34 %
Average Transaction Value : 389166.67
Highest Individual Sales Value : 1050000
Lowest Individual Sales Value : 175000


## Store Summary

In [ ]:
store_sales_tot = sales_data.sum(axis=1)
store_cost_tot = cost_data.sum(axis=1)
store_profit_tot = profit_data.sum(axis=1)
store_margin_tot = np.round((store_profit_tot/store_sales_tot)*100,2)
store_targets_hit = comparison.sum(axis=1)
store_units_tot = units_sold.sum(axis=1)
store_expansion = (store_sales_tot > 2500000) & (store_profit_tot > 700000) & (store_margin_tot > 25)

for i,store in enumerate(stores):
  print("\n",store)
  print("  Total Sales :",store_sales_tot[i])
  print("  Total Cost :",store_cost_tot[i])
  print("  Total Profit :",store_profit_tot[i])
  print("  Profit Margin :",store_margin_tot[i],"%")
  print("  Targets Achieved :",store_targets_hit[i],"/",len(categories))
  print("  Total Units Sold :",store_units_tot[i])
  print("  Expansion Eligible :","Yes" if store_expansion[i] else "No")


 Bengaluru
  Total Sales : 2270000
  Total Cost : 1665000
  Total Profit : 605000
  Profit Margin : 26.65 %
  Targets Achieved : 1 / 6
  Total Units Sold : 1110
  Expansion Eligible : No

 Hyderabad
  Total Sales : 2295000
  Total Cost : 1685000
  Total Profit : 610000
  Profit Margin : 26.58 %
  Targets Achieved : 4 / 6
  Total Units Sold : 1175
  Expansion Eligible : No

 Chennai
  Total Sales : 2310000
  Total Cost : 1710000
  Total Profit : 600000
  Profit Margin : 25.97 %
  Targets Achieved : 2 / 6
  Total Units Sold : 1095
  Expansion Eligible : No

 Mumbai
  Total Sales : 2820000
  Total Cost : 2065000
  Total Profit : 755000
  Profit Margin : 26.77 %
  Targets Achieved : 6 / 6
  Total Units Sold : 1390
  Expansion Eligible : Yes

 Pune
  Total Sales : 1980000
  Total Cost : 1475000
  Total Profit : 505000
  Profit Margin : 25.51 %
  Targets Achieved : 0 / 6
  Total Units Sold : 950
  Expansion Eligible : No


## Category Summary

In [ ]:
cat_sales_tot = sales_data.sum(axis=0)
cat_cost_tot = cost_data.sum(axis=0)
cat_profit_tot = profit_data.sum(axis=0)
cat_margin_tot = np.round((cat_profit_tot/cat_sales_tot)*100,2)
cat_avg_sales = np.round(sales_data.mean(axis=0),2)
cat_targets_hit = comparison.sum(axis=0)
cat_units_tot = units_sold.sum(axis=0)

for i,category in enumerate(categories):
  print("\n",category)
  print("  Total Sales :",cat_sales_tot[i])
  print("  Total Cost :",cat_cost_tot[i])
  print("  Total Profit :",cat_profit_tot[i])
  print("  Profit Margin :",cat_margin_tot[i],"%")
  print("  Average Sales :",cat_avg_sales[i])
  print("  Stores Achieving Target :",cat_targets_hit[i],"/",len(stores))
  print("  Total Units Sold :",cat_units_tot[i])


 Electronics
  Total Sales : 4290000
  Total Cost : 3250000
  Total Profit : 1040000
  Profit Margin : 24.24 %
  Average Sales : 858000.0
  Stores Achieving Target : 3 / 5
  Total Units Sold : 485

 Groceries
  Total Sales : 2185000
  Total Cost : 1660000
  Total Profit : 525000
  Profit Margin : 24.03 %
  Average Sales : 437000.0
  Stores Achieving Target : 2 / 5
  Total Units Sold : 1950

 Clothing
  Total Sales : 1600000
  Total Cost : 1145000
  Total Profit : 455000
  Profit Margin : 28.44 %
  Average Sales : 320000.0
  Stores Achieving Target : 2 / 5
  Total Units Sold : 1240

 Furniture
  Total Sales : 1415000
  Total Cost : 1045000
  Total Profit : 370000
  Profit Margin : 26.15 %
  Average Sales : 283000.0
  Stores Achieving Target : 2 / 5
  Total Units Sold : 345

 Beauty
  Total Sales : 1010000
  Total Cost : 665000
  Total Profit : 345000
  Profit Margin : 34.16 %
  Average Sales : 202000.0
  Stores Achieving Target : 2 / 5
  Total Units Sold : 980

 Sports
  Total Sales : 

## Management Recommendations

In [ ]:
best_store_idx = np.argmax(store_profit_tot)
worst_store_idx = np.argmin(store_profit_tot)
best_cat_idx = np.argmax(cat_profit_tot)
worst_cat_idx = np.argmin(cat_profit_tot)
expansion_stores_final = stores[store_expansion]
promo_categories_final = categories[(cat_avg_sales < 300000) & (cat_margin_tot > 25)]
cost_opt_final = (cost_data > 250000) & (profit_margin < 25)
reorder_final = closing_stock < 25

print("1. Best-performing store :",stores[best_store_idx],"| Profit :",store_profit_tot[best_store_idx])
print("2. Lowest-performing store :",stores[worst_store_idx],"| Profit :",store_profit_tot[worst_store_idx])
print("3. Most profitable category :",categories[best_cat_idx],"| Profit :",cat_profit_tot[best_cat_idx])
print("4. Lowest-profit category :",categories[worst_cat_idx],"| Profit :",cat_profit_tot[worst_cat_idx])
print("5. Store(s) recommended for expansion :",[str(s) for s in expansion_stores_final] if len(expansion_stores_final) else "None")
print("6. Category requiring additional marketing :",[str(c) for c in promo_categories_final] if len(promo_categories_final) else "None")

print("\n7. Store-category combinations needing cost optimization :")
rows,cols = np.where(cost_opt_final)
for r,c in zip(rows,cols):
  print("  -",stores[r],"/",categories[c],"(Cost=",cost_data[r,c],", Margin=",profit_margin[r,c],"%)")

print("\n8. Store-category combinations requiring inventory reorder :")
rows,cols = np.where(reorder_final)
for r,c in zip(rows,cols):
  print("  -",stores[r],"/",categories[c],"(Closing Stock=",closing_stock[r,c],")")

1. Best-performing store : Mumbai | Profit : 755000
2. Lowest-performing store : Pune | Profit : 505000
3. Most profitable category : Electronics | Profit : 1040000
4. Lowest-profit category : Sports | Profit : 340000
5. Store(s) recommended for expansion : ['Mumbai']
6. Category requiring additional marketing : ['Furniture', 'Beauty', 'Sports']

7. Store-category combinations needing cost optimization :
  - Bengaluru / Electronics (Cost= 640000 , Margin= 24.71 %)
  - Hyderabad / Electronics (Cost= 590000 , Margin= 24.36 %)
  - Hyderabad / Groceries (Cost= 350000 , Margin= 23.91 %)
  - Chennai / Electronics (Cost= 700000 , Margin= 23.91 %)
  - Chennai / Groceries (Cost= 295000 , Margin= 24.36 %)
  - Mumbai / Electronics (Cost= 790000 , Margin= 24.76 %)
  - Mumbai / Groceries (Cost= 390000 , Margin= 23.53 %)
  - Pune / Electronics (Cost= 530000 , Margin= 23.19 %)
  - Pune / Groceries (Cost= 310000 , Margin= 23.46 %)

8. Store-category combinations requiring inventory reorder :
  - Pune 

## Final Retail Performance Report

In [ ]:
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("="*40)

print("\nCOMPANY SUMMARY")
print("-"*15)
print("Total Sales :",total_sales)
print("Total Cost :",total_cost)
print("Total Profit :",total_profit)
print("Overall Profit Margin :",overall_margin,"%")

print("\nBEST-PERFORMING STORE")
print("-"*21)
print("Store :",stores[best_store_idx])
print("Sales :",store_sales_tot[best_store_idx])
print("Cost :",store_cost_tot[best_store_idx])
print("Profit :",store_profit_tot[best_store_idx])
print("Profit Margin :",store_margin_tot[best_store_idx],"%")

print("\nMOST PROFITABLE CATEGORY")
print("-"*24)
print("Category :",categories[best_cat_idx])
print("Sales :",cat_sales_tot[best_cat_idx])
print("Cost :",cat_cost_tot[best_cat_idx])
print("Profit :",cat_profit_tot[best_cat_idx])
print("Profit Margin :",cat_margin_tot[best_cat_idx],"%")

print("\nEXPANSION RECOMMENDATIONS")
print("-"*25)
print("Eligible Stores :",[str(s) for s in expansion_stores_final] if len(expansion_stores_final) else "None")

print("\nCOST OPTIMIZATION")
print("-"*17)
rows,cols = np.where(cost_opt_final)
for r,c in zip(rows,cols):
  print("Store:",stores[r],"| Category:",categories[c],"| Cost:",cost_data[r,c],"| Profit Margin:",profit_margin[r,c],"%")

print("\nINVENTORY REORDER")
print("-"*17)
rows,cols = np.where(reorder_final)
for r,c in zip(rows,cols):
  print("Store:",stores[r],"| Category:",categories[c],"| Closing Stock:",closing_stock[r,c],"| Reorder Qty:",reorder_quantity[r,c])

SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales : 11675000
Total Cost : 8600000
Total Profit : 3075000
Overall Profit Margin : 26.34 %

BEST-PERFORMING STORE
---------------------
Store : Mumbai
Sales : 2820000
Cost : 2065000
Profit : 755000
Profit Margin : 26.77 %

MOST PROFITABLE CATEGORY
------------------------
Category : Electronics
Sales : 4290000
Cost : 3250000
Profit : 1040000
Profit Margin : 24.24 %

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores : ['Mumbai']

COST OPTIMIZATION
-----------------
Store: Bengaluru | Category: Electronics | Cost: 640000 | Profit Margin: 24.71 %
Store: Hyderabad | Category: Electronics | Cost: 590000 | Profit Margin: 24.36 %
Store: Hyderabad | Category: Groceries | Cost: 350000 | Profit Margin: 23.91 %
Store: Chennai | Category: Electronics | Cost: 700000 | Profit Margin: 23.91 %
Store: Chennai | Category: Groceries | Cost: 295000 | Profit Margin: 24.36 %
Store: Mumbai | Category: Electronics |

## Business Observations

1. **Mumbai is the strongest overall performer** — it leads in total sales, total profit, and units sold, and comfortably clears the expansion thresholds on sales, profit and margin.
2. **Pune consistently lags the other stores**, showing the lowest total profit and the lowest number of category targets achieved, which points to store-level (not category-level) issues such as footfall or local pricing.
3. **Electronics drives the most revenue but not the best margin** — it is the top category by sales and profit in absolute rupees, but its profit margin trails smaller categories like Groceries and Beauty, so high volume is not translating into proportionally high profitability.
4. **Several store-category combinations fall below the 22% margin bar**, concentrated mainly in Electronics and Furniture — these are the same categories flagged for cost optimization, confirming that cost (not pricing) is the main margin drag.
5. **Inventory reorder needs are spread thin rather than concentrated in one store**, suggesting a general restocking cadence issue across the chain rather than a single store's supply-chain problem.

## Management Recommendations

1. **Prioritize Mumbai for expansion investment** — it is the only store that clears all three expansion criteria (sales, profit, and margin), making it the lowest-risk place to add footprint or headcount first.
2. **Renegotiate supplier costs for Electronics and Furniture** before scaling volume further — both categories repeatedly show high cost against sub-25% margins, so growing sales there without fixing cost will just grow low-margin revenue.
3. **Increase promotional spend on Beauty and other high-margin, low-average-sales categories** — they already convert well on margin, so extra marketing rupees are more likely to translate directly into profit than the same spend on Electronics.